### ISSUE TITLE
Generate proofs

### ISSUE THREAD

**Issue by valavanisleonidas** [cawfree/react-native-webassembly#22]
Hello,

First of all your work is awesome!

I want to generate proofs in react native but snarkjs doesn't work and i am looking for alternatives. If I load the wasm file with this library how do i use groth16 for example to generate the proofs?

**Comment by cawfree** [comment]
Thanks a lot!

Hopefully you can take some inspiration from the following repo:
https://github.com/0xPolygonID/js-sdk-react-native-tools/blob/develop/share%2Fproof%2Fwitness-calculator-native.ts
