### ISSUE TITLE
Provide Example With Local .wasm File

### ISSUE THREAD

**Issue by skyworms** [cawfree/react-native-webassembly#4]
Would it be possible to provide an example using a local `.wasm` file instead of retrieving one with axios? I'm having trouble setting up a test project with a local `.wasm` file and was wondering if it's possible or if axios is actually necessary.

**Comment by cawfree** [comment]
This is a good idea, I'll add an example for this. 🙏

**Comment by cawfree** [comment]
Hey @skyworms!

I've released the ability to import local WebAssembly files as part of [Release 0.2.5](https://github.com/cawfree/react-native-webassembly/releases/tag/v0.2.5), so you'll need to update to the latest version of `react-native-webassembly`. The included example in the repository now shows how to configure a target project to enable local file resolution; check out [this commit](https://github.com/cawfree/react-native-webassembly/pull/5/commits/19b34849570a734a9641c276d164cc0aa08a042a) for a comprehensive example.

Apologies for the turnaround time, hope this didn't block you too badly.

Good luck! If you encounter any issues, please let me know!

**Comment by skyworms** [comment]
It works! Thank you so much!
